# Generated by Django 4.0 on 2021-12-16 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0002_offer_status_alter_offer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='owner_id',
            field=models.ManyToManyField(related_name='user_offer', to=settings.AUTH_USER_MODEL),
        ),
    ]
