# Generated by Django 4.0 on 2021-12-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
