# Generated by Django 4.0 on 2021-12-12 13:41

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0004_rename_body_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_activity', models.CharField(blank=True, default=None, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ManyToManyField(related_name='post', to='connect.Post')),
                ('user', models.ManyToManyField(related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
