# Generated by Django 4.0 on 2021-12-11 13:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='photos/adham-img_Lh0ntBw.jpg', upload_to=accounts.models.User.upload_to),
        ),
    ]
