# Generated by Django 4.0 on 2021-12-11 13:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id_img',
            field=models.ImageField(default='photos/adham-img_Lh0ntBw.jpg', upload_to=accounts.models.User.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='commercial_record_img',
            field=models.ImageField(default='photos/adham-img_Lh0ntBw.jpg', upload_to=accounts.models.User.upload_to),
        ),
    ]
